[project]
name = "all-portals-overlay"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.3",
    "highspy>=1.15.1",
    "matplotlib>=3.11.0",
    "networkx>=3.6.1",
    "numpy>=2.5.1",
    "pulp>=3.3.2",
    "requests>=2.34.2",
]

[dependency-groups]
dev = ["cx-freeze>=8.7.1"]

[tool.cxfreeze]
executables = [{ script = "main.py", target_name = "ap_overlay" }]

[tool.cxfreeze.build_exe]
build_exe = "dist"
include_files = [["templates/", "templates/"]]
